title: Online Fault Detection in Manipulation Tasks via Generative Models
description: |-
  Michael W. Lanighan and Oscar Youngquist

  ICRA 2024
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
github:
  is_project_page: false
